export const nationalityOptions = [
  { key: "sierra-leone", value: "Sierra Leone" },
  { key: "afghanistan", value: "Afghanistan" },
  { key: "albania", value: "Albania" },
  { key: "algeria", value: "Algeria" },
  { key: "andorra", value: "Andorra" },
  { key: "angola", value: "Angola" },
  { key: "antigua-barbuda", value: "Antigua and Barbuda" },
  { key: "argentina", value: "Argentina" },
  { key: "armenia", value: "Armenia" },
  { key: "australia", value: "Australia" },
  { key: "austria", value: "Austria" },
  { key: "azerbaijan", value: "Azerbaijan" },
  { key: "bahamas", value: "Bahamas" },
  { key: "bahrain", value: "Bahrain" },
  { key: "bangladesh", value: "Bangladesh" },
  { key: "barbados", value: "Barbados" },
  { key: "belarus", value: "Belarus" },
  { key: "belgium", value: "Belgium" },
  { key: "belize", value: "Belize" },
  { key: "benin", value: "Benin" },
  { key: "bhutan", value: "Bhutan" },
  { key: "bolivia", value: "Bolivia" },
  { key: "bosnia-herzegovina", value: "Bosnia and Herzegovina" },
  { key: "botswana", value: "Botswana" },
  { key: "brazil", value: "Brazil" },
  { key: "brunei", value: "Brunei" },
  { key: "bulgaria", value: "Bulgaria" },
  { key: "burkina-faso", value: "Burkina Faso" },
  { key: "burundi", value: "Burundi" },
  { key: "cabo-verde", value: "Cabo Verde" },
  { key: "cambodia", value: "Cambodia" },
  { key: "cameroon", value: "Cameroon" },
  { key: "canada", value: "Canada" },
  { key: "central-african-republic", value: "Central African Republic" },
  { key: "chad", value: "Chad" },
  { key: "chile", value: "Chile" },
  { key: "china", value: "China" },
  { key: "colombia", value: "Colombia" },
  { key: "comoros", value: "Comoros" },
  { key: "congo", value: "Congo" },
  { key: "costa-rica", value: "Costa Rica" },
  { key: "croatia", value: "Croatia" },
  { key: "cuba", value: "Cuba" },
  { key: "cyprus", value: "Cyprus" },
  { key: "czech-republic", value: "Czech Republic" },
  { key: "denmark", value: "Denmark" },
  { key: "djibouti", value: "Djibouti" },
  { key: "dominica", value: "Dominica" },
  { key: "dominican-republic", value: "Dominican Republic" },
  { key: "ecuador", value: "Ecuador" },
  { key: "egypt", value: "Egypt" },
  { key: "el-salvador", value: "El Salvador" },
  { key: "equatorial-guinea", value: "Equatorial Guinea" },
  { key: "eritrea", value: "Eritrea" },
  { key: "estonia", value: "Estonia" },
  { key: "eswatini", value: "Eswatini" },
  { key: "ethiopia", value: "Ethiopia" },
  { key: "fiji", value: "Fiji" },
  { key: "finland", value: "Finland" },
  { key: "france", value: "France" },
  { key: "gabon", value: "Gabon" },
  { key: "gambia", value: "Gambia" },
  { key: "georgia", value: "Georgia" },
  { key: "germany", value: "Germany" },
  { key: "ghana", value: "Ghana" },
  { key: "greece", value: "Greece" },
  { key: "grenada", value: "Grenada" },
  { key: "guatemala", value: "Guatemala" },
  { key: "guinea", value: "Guinea" },
  { key: "guinea-bissau", value: "Guinea-Bissau" },
  { key: "guyana", value: "Guyana" },
  { key: "haiti", value: "Haiti" },
  { key: "honduras", value: "Honduras" },
  { key: "hungary", value: "Hungary" },
  { key: "iceland", value: "Iceland" },
  { key: "india", value: "India" },
  { key: "indonesia", value: "Indonesia" },
  { key: "iran", value: "Iran" },
  { key: "iraq", value: "Iraq" },
  { key: "ireland", value: "Ireland" },
  { key: "israel", value: "Israel" },
  { key: "italy", value: "Italy" },
  { key: "jamaica", value: "Jamaica" },
  { key: "japan", value: "Japan" },
  { key: "jordan", value: "Jordan" },
  { key: "kazakhstan", value: "Kazakhstan" },
  { key: "kenya", value: "Kenya" },
  { key: "kiribati", value: "Kiribati" },
  { key: "korea-north", value: "Korea, North" },
  { key: "korea-south", value: "Korea, South" },
  { key: "kosovo", value: "Kosovo" },
  { key: "kuwait", value: "Kuwait" },
  { key: "kyrgyzstan", value: "Kyrgyzstan" },
  { key: "laos", value: "Laos" },
  { key: "latvia", value: "Latvia" },
  { key: "lebanon", value: "Lebanon" },
  { key: "lesotho", value: "Lesotho" },
  { key: "liberia", value: "Liberia" },
  { key: "libya", value: "Libya" },
  { key: "liechtenstein", value: "Liechtenstein" },
  { key: "lithuania", value: "Lithuania" },
  { key: "luxembourg", value: "Luxembourg" },
  { key: "madagascar", value: "Madagascar" },
  { key: "malawi", value: "Malawi" },
  { key: "malaysia", value: "Malaysia" },
  { key: "maldives", value: "Maldives" },
  { key: "mali", value: "Mali" },
  { key: "malta", value: "Malta" },
  { key: "marshall-islands", value: "Marshall Islands" },
  { key: "mauritania", value: "Mauritania" },
  { key: "mauritius", value: "Mauritius" },
  { key: "mexico", value: "Mexico" },
  { key: "micronesia", value: "Micronesia" },
  { key: "moldova", value: "Moldova" },
  { key: "monaco", value: "Monaco" },
  { key: "mongolia", value: "Mongolia" },
  { key: "montenegro", value: "Montenegro" },
  { key: "morocco", value: "Morocco" },
  { key: "mozambique", value: "Mozambique" },
  { key: "myanmar", value: "Myanmar" },
  { key: "namibia", value: "Namibia" },
  { key: "nauru", value: "Nauru" },
  { key: "nepal", value: "Nepal" },
  { key: "netherlands", value: "Netherlands" },
  { key: "new-zealand", value: "New Zealand" },
  { key: "nicaragua", value: "Nicaragua" },
  { key: "niger", value: "Niger" },
  { key: "nigeria", value: "Nigeria" },
  { key: "north-macedonia", value: "North Macedonia" },
  { key: "norway", value: "Norway" },
  { key: "oman", value: "Oman" },
  { key: "pakistan", value: "Pakistan" },
  { key: "palau", value: "Palau" },
  { key: "panama", value: "Panama" },
  { key: "papua-new-guinea", value: "Papua New Guinea" },
  { key: "paraguay", value: "Paraguay" },
  { key: "peru", value: "Peru" },
  { key: "philippines", value: "Philippines" },
  { key: "poland", value: "Poland" },
  { key: "portugal", value: "Portugal" },
  { key: "qatar", value: "Qatar" },
  { key: "romania", value: "Romania" },
  { key: "russia", value: "Russia" },
  { key: "rwanda", value: "Rwanda" },
  { key: "saint-kitts-nevis", value: "Saint Kitts and Nevis" },
  { key: "saint-lucia", value: "Saint Lucia" },
  { key: "saint-vincent-grenadines", value: "Saint Vincent and the Grenadines" },
  { key: "samoa", value: "Samoa" },
  { key: "san-marino", value: "San Marino" },
  { key: "sao-tome-principe", value: "Sao Tome and Principe" },
  { key: "saudi-arabia", value: "Saudi Arabia" },
  { key: "senegal", value: "Senegal" },
  { key: "serbia", value: "Serbia" },
  { key: "seychelles", value: "Seychelles" },
  { key: "singapore", value: "Singapore" },
  { key: "slovakia", value: "Slovakia" },
  { key: "slovenia", value: "Slovenia" },
  { key: "solomon-islands", value: "Solomon Islands" },
  { key: "somalia", value: "Somalia" },
  { key: "south-africa", value: "South Africa" },
  { key: "south-sudan", value: "South Sudan" },
  { key: "spain", value: "Spain" },
  { key: "sri-lanka", value: "Sri Lanka" },
  { key: "sudan", value: "Sudan" },
  { key: "suriname", value: "Suriname" },
  { key: "sweden", value: "Sweden" },
  { key: "switzerland", value: "Switzerland" },
  { key: "syria", value: "Syria" },
  { key: "taiwan", value: "Taiwan" },
  { key: "tajikistan", value: "Tajikistan" },
  { key: "tanzania", value: "Tanzania" },
  { key: "thailand", value: "Thailand" },
  { key: "timor-leste", value: "Timor-Leste" },
  { key: "togo", value: "Togo" },
  { key: "tonga", value: "Tonga" },
  { key: "trinidad-tobago", value: "Trinidad and Tobago" },
  { key: "tunisia", value: "Tunisia" },
  { key: "turkey", value: "Turkey" },
  { key: "turkmenistan", value: "Turkmenistan" },
  { key: "tuvalu", value: "Tuvalu" },
  { key: "uganda", value: "Uganda" },
  { key: "ukraine", value: "Ukraine" },
  { key: "united-arab-emirates", value: "United Arab Emirates" },
  { key: "united-kingdom", value: "United Kingdom" },
  { key: "united-states", value: "United States" },
  { key: "uruguay", value: "Uruguay" },
  { key: "uzbekistan", value: "Uzbekistan" },
  { key: "vanuatu", value: "Vanuatu" },
  { key: "vatican-city", value: "Vatican City" },
  { key: "venezuela", value: "Venezuela" },
  { key: "vietnam", value: "Vietnam" },
  { key: "yemen", value: "Yemen" },
  { key: "zambia", value: "Zambia" },
  { key: "zimbabwe", value: "Zimbabwe" }
];
