import { supabase } from "@/lib/supabase"

// Expanded recipient types to support cross-module notifications (admins, teachers, parents, MBSSE, etc.)
type RecipientType = "admin" | "teacher" | "parent" | "mbsse" | "system"

enum NotificationType {
  Welcome = "welcome",
  PasswordChange = "password_change",
  System = "system",
  Info = "info",
}

interface CreateNotificationParams {
  // New unified recipient model
  recipient_type?: RecipientType
  recipient_id?: string

  // Back-compat inputs (will be mapped to recipient_type/id)
  adminId?: string
  teacherId?: string

  // Core payload
  title: string
  message: string
  type: NotificationType | 'welcome' | 'password_change' | 'system' | 'info'
  action_url?: string

  // Optional sender metadata for cross-module notifications
  sender_type?: RecipientType
  sender_id?: string

  school_id?: string // Added school_id for multi-tenancy
}

// Export the createNotification function for manual testing with unified recipient model
export async function createNotification(params: CreateNotificationParams) {
  try {
    const {
      recipient_type: providedRecipientType,
      recipient_id: providedRecipientId,
      adminId,
      teacherId,
      title,
      message,
      type,
      action_url,
      sender_type,
      sender_id,
      school_id,
    } = params

    // Resolve recipient from unified or legacy fields
    let recipient_type: RecipientType | undefined = providedRecipientType
    let recipient_id: string | undefined = providedRecipientId

    if (!recipient_type || !recipient_id) {
      if (adminId) {
        recipient_type = "admin"
        recipient_id = adminId
      } else if (teacherId) {
        recipient_type = "teacher"
        recipient_id = teacherId
      }
    }

    if (!recipient_type || !recipient_id) {
      throw new Error("recipient_type and recipient_id (or adminId/teacherId) are required")
    }

    // Note: ID is auto-generated by Supabase (UUID)
    const currentDate = new Date().toISOString()

    const notificationData: Record<string, any> = {
      recipient_type,
      recipient_id,
      title,
      message,
      type,
      read: false,
      created_at: currentDate,
      ...(action_url && { action_url }),
      ...(sender_type && { sender_type }),
      ...(sender_id && { sender_id }),
      ...(school_id && { school_id }),
    }

    // Backward compatibility: also persist legacy fields so existing client queries still work
    // Note: The new schema might not have these fields if we strictly followed the guide.
    // The guide has 'admin_id' and 'teacher_id' as text columns for legacy support.
    if (recipient_type === "admin") {
      notificationData.admin_id = recipient_id
    }
    if (recipient_type === "teacher") {
      notificationData.teacher_id = recipient_id
    }

    const { data, error } = await supabase
      .from('notifications')
      .insert(notificationData)
      .select('id')
      .single()

    if (error) throw error

    return data.id
  } catch (error) {
    console.error('Error creating notification:', error)
    throw error
  }
}

export async function sendWelcomeNotification(adminId: string, adminName: string, adminEmail: string) {
  try {
    // Create notification in Supabase for admin
    const notificationId = await createNotification({
      recipient_type: "admin",
      recipient_id: adminId,
      title: "Welcome to Skultɛk!",
      message: "Thank you for using Skultɛk School Management System. We're excited to have you on board!",
      type: NotificationType.Welcome,
      action_url: "/dashboard",
      sender_type: "system",
    })

    // Send welcome email
    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'welcome', email: adminEmail, name: adminName, adminId }),
    })

    // Best-effort logging
    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Error sending welcome notification:', error)
    throw error
  }
}

export async function sendPasswordChangeNotification(adminId: string, adminName: string, adminEmail: string) {
  try {
    const notificationId = await createNotification({
      recipient_type: "admin",
      recipient_id: adminId,
      title: "Password Changed",
      message: "Your password was recently changed. If this wasn't you, please contact support immediately.",
      type: NotificationType.PasswordChange,
      action_url: "/profile",
      sender_type: "system",
    })

    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'password_change', email: adminEmail, name: adminName, adminId }),
    })

    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Error sending password change notification:', error)
    throw error
  }
}

// Admin-originated notification to a teacher about subject assignment
export async function sendTeacherSubjectAssignmentNotification(
  teacherId: string,
  teacherName: string,
  teacherEmail: string,
  subjectName: string,
  subjectCode: string,
  schoolId?: string
) {
  try {
    const notificationId = await createNotification({
      recipient_type: "teacher",
      recipient_id: teacherId,
      title: "Subject Assignment",
      message: `You have been assigned to teach ${subjectName} (${subjectCode}). Please review your teaching schedule and prepare accordingly.`,
      type: NotificationType.System,
      action_url: "/subjects",
      sender_type: "admin",
      school_id: schoolId
    })

    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: 'teacher_assignment',
        email: teacherEmail,
        name: teacherName,
        teacherId,
        subjectName,
        subjectCode,
      }),
    })

    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Error sending teacher subject assignment notification:', error)
    throw error
  }
}

// Admin-originated notification to a teacher about subject unassignment
export async function sendTeacherSubjectUnassignmentNotification(
  teacherId: string,
  teacherName: string,
  teacherEmail: string,
  subjectName: string,
  subjectCode: string,
  schoolId?: string
) {
  try {
    const notificationId = await createNotification({
      recipient_type: "teacher",
      recipient_id: teacherId,
      title: "Subject Unassignment",
      message: `You have been unassigned from teaching ${subjectName} (${subjectCode}). Please contact the administration if you have any questions.`,
      type: NotificationType.System,
      action_url: "/subjects",
      sender_type: "admin",
      school_id: schoolId
    })

    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: 'teacher_unassignment',
        email: teacherEmail,
        name: teacherName,
        teacherId,
        subjectName,
        subjectCode,
      }),
    })

    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Error sending teacher subject unassignment notification:', error)
    throw error
  }
}

// Admin-originated notification to a teacher about class assignment
export async function sendTeacherClassAssignmentNotification(
  teacherId: string,
  teacherName: string,
  teacherEmail: string,
  className: string,
  classLevel: string,
  schoolId?: string
) {
  try {
    const notificationId = await createNotification({
      recipient_type: "teacher",
      recipient_id: teacherId,
      title: "Class Assignment",
      message: `You have been assigned as the class teacher for ${className} (${classLevel}). Please review your class details and prepare for the academic year.`,
      type: NotificationType.System,
      action_url: "/classes",
      sender_type: "admin",
      school_id: schoolId
    })

    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: 'teacher_class_assignment',
        email: teacherEmail,
        name: teacherName,
        teacherId,
        className,
        classLevel,
      }),
    })

    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Error sending teacher class assignment notification:', error)
    throw error
  }
}

// Test function to verify notification system
export async function testNotificationSystem(adminId: string, adminName: string, adminEmail: string) {
  try {
    const notificationId = await createNotification({
      recipient_type: "admin",
      recipient_id: adminId,
      title: "Test Notification",
      message: "This is a test notification to verify the system is working.",
      type: NotificationType.System,
      action_url: "/dashboard",
      sender_type: "system",
    })

    const emailResponse = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'welcome', email: adminEmail, name: adminName, adminId }),
    })

    try { await emailResponse.json() } catch { }

    return notificationId
  } catch (error) {
    console.error('Test notification system failed:', error)
    throw error
  }
}